// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void maa() {
    driver.get("http://localhost:4200/cadastro-produto/cadastro-produto");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("maça");
    driver.findElement(By.id("descriçao produto")).click();
    driver.findElement(By.id("descriçao produto")).sendKeys("Maçã produzida no imalaia de forma organica e rigorosa com um controle de qualidade unico!");
    driver.findElement(By.id("imagem1")).click();
    driver.findElement(By.id("imagem1")).sendKeys("https://images.unsplash.com/photo-1590005354167-6da97870c757?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8YXBwbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60");
    driver.findElement(By.id("imagem2")).click();
    driver.findElement(By.id("imagem2")).sendKeys("https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8YXBwbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60");
    driver.findElement(By.id("imagem3")).click();
    driver.findElement(By.id("imagem3")).sendKeys("https://images.unsplash.com/photo-1584306670957-acf935f5033c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8YXBwbGV8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60");
    driver.findElement(By.id("preco")).click();
    driver.findElement(By.id("preco")).sendKeys("8");
    driver.findElement(By.id("quantidade")).click();
    driver.findElement(By.id("quantidade")).sendKeys("9087");
    driver.findElement(By.id("estoque")).click();
    driver.findElement(By.id("escolha de categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("escolha de categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Frutas']")).click();
    }
    driver.findElement(By.id("escolha de categoria")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(13) > .btn")).click();
    driver.findElement(By.cssSelector(".modal")).click();
  }
  @Test
  public void laranjaOrganica() {
    driver.get("http://localhost:4200/cadastro-produto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Laranja orgânica");
    driver.findElement(By.id("descriçao produto")).click();
    driver.findElement(By.id("descriçao produto")).sendKeys("Laranja produzida de forma orgânica e natural");
    driver.findElement(By.id("imagem1")).click();
    driver.findElement(By.id("imagem1")).sendKeys("https://images.unsplash.com/photo-1580052614034-c55d20bfee3b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8b3JhbmdlfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem2")).click();
    driver.findElement(By.id("imagem2")).sendKeys("https://images.unsplash.com/photo-1547514701-42782101795e?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8b3JhbmdlfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem3")).click();
    driver.findElement(By.id("imagem3")).sendKeys("https://images.unsplash.com/photo-1579169326371-ccb4e63f7889?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OHx8b3JhbmdlfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("preco")).click();
    driver.findElement(By.id("preco")).sendKeys("8");
    driver.findElement(By.id("quantidade")).click();
    driver.findElement(By.id("quantidade")).sendKeys("298");
    driver.findElement(By.id("estoque")).click();
    driver.findElement(By.id("escolha de categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("escolha de categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Frutas']")).click();
    }
    driver.findElement(By.id("escolha de categoria")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(13) > .btn")).click();
    driver.findElement(By.cssSelector(".modal")).click();
  }
  @Test
  public void mirtiloAmericano() {
    driver.get("http://localhost:4200/cadastro-produto");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Mirtilo Americano");
    driver.findElement(By.id("descriçao produto")).click();
    driver.findElement(By.id("descriçao produto")).sendKeys("Mirtilo Americano produzido no Brasil de forma controlada e com ambientes simulados.");
    driver.findElement(By.id("imagem1")).click();
    driver.findElement(By.id("imagem1")).sendKeys("https://images.unsplash.com/photo-1587242155092-d126d2db782f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8Ymx1ZWJlcnJ5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem2")).click();
    driver.findElement(By.id("imagem2")).sendKeys("https://images.unsplash.com/photo-1566400628146-ae8f27849e90?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8Ymx1ZWJlcnJ5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem3")).click();
    driver.findElement(By.id("imagem3")).sendKeys("https://images.unsplash.com/photo-1577916082233-f97ed22e4df8?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NXx8Ymx1ZWJlcnJ5fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("preco")).click();
    driver.findElement(By.id("preco")).sendKeys("12");
    driver.findElement(By.id("quantidade")).click();
    driver.findElement(By.id("quantidade")).sendKeys("890");
    driver.findElement(By.id("estoque")).click();
    driver.findElement(By.id("escolha de categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("escolha de categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Frutas']")).click();
    }
    driver.findElement(By.id("escolha de categoria")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(13) > .btn")).click();
    driver.findElement(By.cssSelector(".modal")).click();
  }
  @Test
  public void morango() {
    driver.get("http://localhost:4200/cadastro-produto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Morango");
    driver.findElement(By.id("descriçao produto")).click();
    driver.findElement(By.id("descriçao produto")).sendKeys("Morango produzido de forma natural.");
    driver.findElement(By.id("imagem1")).click();
    driver.findElement(By.id("imagem1")).sendKeys("https://images.unsplash.com/photo-1592457765434-70aacc2da743?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8c3RyYXdiZXJyeXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem2")).click();
    driver.findElement(By.id("imagem2")).sendKeys("https://images.unsplash.com/photo-1518635017498-87f514b751ba?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OHx8c3RyYXdiZXJyeXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem3")).click();
    driver.findElement(By.id("imagem3")).sendKeys("https://images.unsplash.com/photo-1568966299181-bb7282cc84f0?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OXx8c3RyYXdiZXJyeXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("preco")).click();
    driver.findElement(By.id("preco")).sendKeys("5");
    driver.findElement(By.id("quantidade")).click();
    driver.findElement(By.id("quantidade")).sendKeys("987");
    driver.findElement(By.id("estoque")).click();
    driver.findElement(By.id("escolha de categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("escolha de categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Frutas']")).click();
    }
    driver.findElement(By.id("escolha de categoria")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(13) > .btn")).click();
    driver.findElement(By.cssSelector(".modal")).click();
  }
  @Test
  public void pessego() {
    driver.get("http://localhost:4200/cadastro-produto");
    driver.manage().window().setSize(new Dimension(697, 735));
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Pessego");
    driver.findElement(By.id("descriçao produto")).click();
    driver.findElement(By.id("descriçao produto")).sendKeys("Pessego produzido com pesticidas e produtos totalmente regulamentados.");
    driver.findElement(By.id("imagem1")).click();
    driver.findElement(By.id("imagem1")).sendKeys("https://images.unsplash.com/photo-1595124245030-41448b199d6d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8cGVhY2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem2")).click();
    driver.findElement(By.id("imagem2")).sendKeys("https://images.unsplash.com/photo-1595743825637-cdafc8ad4173?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8cGVhY2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("imagem3")).click();
    driver.findElement(By.id("imagem3")).sendKeys("https://images.unsplash.com/photo-1602813812581-0713dae489da?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8cGVhY2h8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60");
    driver.findElement(By.id("preco")).click();
    driver.findElement(By.id("preco")).sendKeys("12");
    driver.findElement(By.id("quantidade")).click();
    driver.findElement(By.id("quantidade")).sendKeys("897");
    driver.findElement(By.id("estoque")).click();
    driver.findElement(By.id("escolha de categoria")).click();
    {
      WebElement dropdown = driver.findElement(By.id("escolha de categoria"));
      dropdown.findElement(By.xpath("//option[. = 'Frutas']")).click();
    }
    driver.findElement(By.id("escolha de categoria")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(13) > .btn")).click();
    driver.findElement(By.cssSelector(".modal")).click();
  }
}
